# Generated by Django 5.0.6 on 2024-08-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_book_price_alter_book_retal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='retal_period_type',
            field=models.CharField(blank=True, choices=[('hour', 'الساعه'), ('year', 'السنه'), ('day', 'اليوم')], max_length=50, null=True),
        ),
    ]
