# Generated by Django 5.0.6 on 2024-08-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_book_retal_period_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='retal_period_type',
            field=models.CharField(blank=True, choices=[('الساعه', 'الساعه'), ('السنه', 'السنه'), ('اليوم', 'اليوم')], max_length=50, null=True),
        ),
    ]
